global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'eureka'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    eureka_sd_configs:
      - server: 'http://localhost:8761/eureka' # URL do servidor Eureka
        refresh_interval: 30s # Intervalo de atualização
    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_ip_addr, __meta_eureka_app_instance_port]
        separator: ':'
        target_label: '__address__'
        regex: '([^:]+):([^:]+)'
        replacement: '${1}:${2}'
        action: 'replace'
      - source_labels: [__meta_eureka_app_instance_appname]
        target_label: 'job'
      - source_labels: [__meta_eureka_app_instance_status]
        action: 'keep'
        regex: 'UP'
